--
-- PostgreSQL database dump
--

-- Dumped from database version 16.9 (Ubuntu 16.9-0ubuntu0.24.04.1)
-- Dumped by pg_dump version 16.9 (Ubuntu 16.9-0ubuntu0.24.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: deductions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.deductions (
    id bigint NOT NULL,
    code character varying(255) NOT NULL,
    deduction_name character varying(255) NOT NULL,
    percentage numeric(38,2) NOT NULL
);


ALTER TABLE public.deductions OWNER TO postgres;

--
-- Name: deductions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.deductions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.deductions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: employee_roles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.employee_roles (
    employee_id bigint NOT NULL,
    role character varying(255)
);


ALTER TABLE public.employee_roles OWNER TO postgres;

--
-- Name: employees; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.employees (
    id bigint NOT NULL,
    code character varying(255) NOT NULL,
    date_of_birth date NOT NULL,
    email character varying(255) NOT NULL,
    first_name character varying(255) NOT NULL,
    last_name character varying(255) NOT NULL,
    mobile character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    status character varying(255),
    CONSTRAINT employees_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'DISABLED'::character varying])::text[])))
);


ALTER TABLE public.employees OWNER TO postgres;

--
-- Name: employees_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.employees ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.employees_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: employments; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.employments (
    id bigint NOT NULL,
    base_salary numeric(38,2) NOT NULL,
    code character varying(255) NOT NULL,
    department character varying(255) NOT NULL,
    joining_date date NOT NULL,
    "position" character varying(255) NOT NULL,
    status character varying(255),
    employee_id bigint NOT NULL,
    CONSTRAINT employments_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'INACTIVE'::character varying])::text[])))
);


ALTER TABLE public.employments OWNER TO postgres;

--
-- Name: employments_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.employments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.employments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: messages; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.messages (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    message text NOT NULL,
    month integer NOT NULL,
    sent_at timestamp(6) without time zone,
    status character varying(255),
    year integer NOT NULL,
    employee_id bigint NOT NULL,
    CONSTRAINT messages_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'SENT'::character varying, 'FAILED'::character varying])::text[])))
);


ALTER TABLE public.messages OWNER TO postgres;

--
-- Name: messages_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.messages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.messages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: payslips; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.payslips (
    id bigint NOT NULL,
    employee_taxed_amount numeric(38,2) NOT NULL,
    gross_salary numeric(38,2) NOT NULL,
    house_amount numeric(38,2) NOT NULL,
    medical_insurance_amount numeric(38,2) NOT NULL,
    month integer NOT NULL,
    net_salary numeric(38,2) NOT NULL,
    other_taxed_amount numeric(38,2) NOT NULL,
    pension_amount numeric(38,2) NOT NULL,
    status character varying(255),
    transport_amount numeric(38,2) NOT NULL,
    year integer NOT NULL,
    employee_id bigint NOT NULL,
    CONSTRAINT payslips_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'PAID'::character varying])::text[])))
);


ALTER TABLE public.payslips OWNER TO postgres;

--
-- Name: payslips_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.payslips ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payslips_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: deductions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.deductions (id, code, deduction_name, percentage) FROM stdin;
1	DED-91924F24	Employee Tax	30.00
2	DED-2FFBBB9D	Pension	6.00
3	DED-0447C3A4	Medical Insurance	5.00
4	DED-6328C0BA	Housing	14.00
5	DED-AB83740D	Transport	14.00
6	DED-EC47211D	Others	5.00
\.


--
-- Data for Name: employee_roles; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.employee_roles (employee_id, role) FROM stdin;
1	ADMIN
2	EMPLOYEE
\.


--
-- Data for Name: employees; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.employees (id, code, date_of_birth, email, first_name, last_name, mobile, password, status) FROM stdin;
1	EMP-987CA9F2	2006-05-29	shemafranko0987@gmail.com	shema	frank	+250722505709	$2a$10$ITpJyJMuAfuC2w4B57.MvuFTiVj6izlbT4diwZ0PqsqixtjoohNDy	ACTIVE
2	EMP-AE4664F3	2000-05-29	titijado@gmail.com	string	string	0731079001	$2a$10$o3oTQkjSGhyPOtoSUVzWheL7Ek4WJcVtJpJV9BcTx2u8ZlehaHDBq	ACTIVE
\.


--
-- Data for Name: employments; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.employments (id, base_salary, code, department, joining_date, "position", status, employee_id) FROM stdin;
1	100000.00	EMP-23214ECF	IT	2025-03-29	CEO	ACTIVE	2
\.


--
-- Data for Name: messages; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.messages (id, created_at, message, month, sent_at, status, year, employee_id) FROM stdin;
1	2025-05-29 19:04:31.361415	Dear string, your salary for MARCH/2025 from RCA amounting to 82000.00 has been credited to your account EMP-AE4664F3 successfully.	3	2025-05-29 19:04:36.941957	SENT	2025	2
\.


--
-- Data for Name: payslips; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.payslips (id, employee_taxed_amount, gross_salary, house_amount, medical_insurance_amount, month, net_salary, other_taxed_amount, pension_amount, status, transport_amount, year, employee_id) FROM stdin;
1	30000.00	128000.00	14000.00	5000.00	3	82000.00	5000.00	6000.00	PAID	14000.00	2025	2
\.


--
-- Name: deductions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.deductions_id_seq', 6, true);


--
-- Name: employees_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.employees_id_seq', 2, true);


--
-- Name: employments_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.employments_id_seq', 1, true);


--
-- Name: messages_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.messages_id_seq', 1, true);


--
-- Name: payslips_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.payslips_id_seq', 1, true);


--
-- Name: deductions deductions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.deductions
    ADD CONSTRAINT deductions_pkey PRIMARY KEY (id);


--
-- Name: employees employees_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employees
    ADD CONSTRAINT employees_pkey PRIMARY KEY (id);


--
-- Name: employments employments_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employments
    ADD CONSTRAINT employments_pkey PRIMARY KEY (id);


--
-- Name: messages messages_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.messages
    ADD CONSTRAINT messages_pkey PRIMARY KEY (id);


--
-- Name: payslips payslips_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.payslips
    ADD CONSTRAINT payslips_pkey PRIMARY KEY (id);


--
-- Name: deductions uk2nkwevgjfin5vjs2792dsmw4m; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.deductions
    ADD CONSTRAINT uk2nkwevgjfin5vjs2792dsmw4m UNIQUE (deduction_name);


--
-- Name: employees uk3um79qgwg340lpaw7phtwudtc; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employees
    ADD CONSTRAINT uk3um79qgwg340lpaw7phtwudtc UNIQUE (code);


--
-- Name: employments uk3v0y1vqxyua9lvkiew11mnw1o; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employments
    ADD CONSTRAINT uk3v0y1vqxyua9lvkiew11mnw1o UNIQUE (code);


--
-- Name: payslips ukfdj0pams7wwy6fqdrhabe43fs; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.payslips
    ADD CONSTRAINT ukfdj0pams7wwy6fqdrhabe43fs UNIQUE (employee_id, month, year);


--
-- Name: deductions ukh8uwnwyducexwvadtyg7f3qes; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.deductions
    ADD CONSTRAINT ukh8uwnwyducexwvadtyg7f3qes UNIQUE (code);


--
-- Name: employees ukj9xgmd0ya5jmus09o0b8pqrpb; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employees
    ADD CONSTRAINT ukj9xgmd0ya5jmus09o0b8pqrpb UNIQUE (email);


--
-- Name: messages fk1q671yj3ssisaipaue47bgvdc; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.messages
    ADD CONSTRAINT fk1q671yj3ssisaipaue47bgvdc FOREIGN KEY (employee_id) REFERENCES public.employees(id);


--
-- Name: employee_roles fk3uwwaxeiucvfixgd45etkjgmg; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employee_roles
    ADD CONSTRAINT fk3uwwaxeiucvfixgd45etkjgmg FOREIGN KEY (employee_id) REFERENCES public.employees(id);


--
-- Name: employments fkd0t2nvcnyco5o5kj188l4fsql; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employments
    ADD CONSTRAINT fkd0t2nvcnyco5o5kj188l4fsql FOREIGN KEY (employee_id) REFERENCES public.employees(id);


--
-- Name: payslips fki2u90djkfkqooebb9b26gxqmi; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.payslips
    ADD CONSTRAINT fki2u90djkfkqooebb9b26gxqmi FOREIGN KEY (employee_id) REFERENCES public.employees(id);


--
-- PostgreSQL database dump complete
--

